# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaAviso.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAviso(object):

    def setupUi(self, DialogAviso):
        DialogAviso.setObjectName("DialogAviso")
        DialogAviso.resize(400, 300)
        self.labelInfo = QtWidgets.QLabel(DialogAviso)
        self.labelInfo.setGeometry(QtCore.QRect(54, 60, 301, 111))
        self.labelInfo.setObjectName("labelInfo")
        self.pushButtonOK = QtWidgets.QPushButton(DialogAviso)
        self.pushButtonOK.setGeometry(QtCore.QRect(160, 220, 93, 28))
        self.pushButtonOK.setObjectName("pushButtonOK")

        self.retranslateUi(DialogAviso)
        QtCore.QMetaObject.connectSlotsByName(DialogAviso)

    def retranslateUi(self, DialogAviso):
        _translate = QtCore.QCoreApplication.translate
        DialogAviso.setWindowTitle(_translate("DialogAviso", "AVISO"))
        self.labelInfo.setText(_translate("DialogAviso", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonOK.setText(_translate("DialogAviso", "OK"))
